version: "3.9"

services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/uploads
    working_dir: /app
    environment:
      - DB_HOST=sql3.freesqldatabase.com
      - DB_USER=sql3771034
      - DB_PASSWORD=QpfxeR5MqR
      - DB_NAME=sql3771034
    command: node server.js

  frontend:
    build: ./client
    container_name: app-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
